version: 2
updates:
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: lint-staged
    versions:
    - 10.5.3
